console.group("Post1")
console.log("Post Created")
console.log("Post Edited")
console.log('post Deleted')
console.groupEnd('postend')
console.log("1234".split('').reverse().join(''))
console.log("sathiya".split('').reverse().join(""))
console.log("Rockshana".split('').reverse().join(''))
console.log("harshith".split('').reverse().join(''))
